name: application_one
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  form_validator: ^2.1.1
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.3
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  jiffy: ^6.3.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Path to your app icon
  adaptive_icon_foreground: "assets/images/logo.png" # Optional for Android
  adaptive_icon_background: "assets/images/logo.png" # Optional for Android
  min_sdk_android: 21 # Optional
  remove_alpha_ios: true 
